name: Homes
version: '1.0-SNAPSHOT'
main: homes.homes.Homes
api-version: 1.19
authors: [Eliott Deriaz]
commands:
  sethome:
    description: Set home for the command sender
    usage: /sethome
    aliases: sh
    permission: homes.homes.setHome
    permission-message: You don't have the permission to use this command.
  home:
    description: Teleport to the home for the command sender
    usage: /home
    aliases: h
    permission: homes.homes.home
    permission-message: You don't have the permission to use this command.